### ISSUE TITLE
Make plugin administration compatible for CMsimple_XH 1.7.x

### ISSUE THREAD

**Issue by lck-git** [cmb69/recaptcha_xh#2]
See: https://cmsimpleforum.com/viewtopic.php?f=12&t=14347&p=69378#p69378
Betrifft auch Version von [bbfriend](https://github.com/bbfriend/recaptcha_xh).

**Comment by cmb69** [comment]
Thanks for the report! However, this repo is obsolete since a long time, and has been superseeded by https://github.com/bbfriend/recaptcha_xh.
